# cloudbuild.yaml

steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/hr-insight-repo/mlrs:latest', '.']
  
  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/hr-insight-repo/mlrs:latest']
  
  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mlrs' # Service name
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/hr-insight-repo/mlrs:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=10000'
      - '--memory=4Gi' # Increased memory from previous steps
      - '--cpu=4' # Increased CPU from previous steps

# Build and push the final image
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/hr-insight-repo/mlrs:latest'

# Add this section to resolve the error
options:
  logging: CLOUD_LOGGING_ONLY